# List of predefined properties to consider: https://ktor.io/docs/server-configuration-file.html#predefined-properties
ktor:
  environment: "$KTOR_ENV:dev"
  deployment:
    host: localhost
    port: "$PORT:8080"
  application:
    modules:
      - no.stackcanary.config.AppConfigKt.mainModule

postgres:
  url: "$DB_URL:jdbc:postgresql://localhost:5432/playground_db"
  user: "$DB_USER:postgres"
  password: "$DB_PW:admin"

oauth:
  issuerUrl: "$ISSUER_URL:http://localhost:9000"
  clientId: "$CLIENT_ID:resource-server-client"
  clientSecret: "$CLIENT_SECRET:resource-server-secret"