openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /:
    get:
      summary: Returns a welcoming text.
      description: Marked for removal
      responses:
        '200': # status code
          description: A welcoming text
          content:
            application/json:
              schema:
                type: string


